### PR TITLE
Fixed issue

### PR DESCRIPTION
**Pull request by mLoDar**
Renamed variables and methods in order to follow the naming conventions.
This commit should fix issue #14 and #15 .

### CODE REVIEW

**Comment by mLoDar** [comment]
Commit 503eb09bc125cd1434f99deb7cf6a482de5734da should fix issue #20.

Please let me know what you guys think of the style/approach I chose for cleaning up the code.
Do you have ideas on how to improve it or did you notice things I should different in the future?

I am looking forward to your hones feedback :smiley:

**Comment by Guy-S-glitch** [comment]
hi @mLoDar.
i saw your pr and looked great, really appreciate your help and loved the changes you did to the names 👍 .

**Comment by Guy-S-glitch** [comment]
also @mLoDar figured it'll be useful to inform you that you could run the project yourself, the use with sql is only to upload the data to the server and to retrieve back to the project. 
without the sql the project will work the same except you'll be needed to fill the data yourself.
also your style of coding is very impressive and i'll try to adopt it, it's very cool and readable 👍 .

**Comment by mLoDar** [comment]
hey @Guy-S-glitch 
Thanks for the information regarding the sql within the project. Haven't tried it out yet, but this will definitely come in handy : )
I am also glad that you like the way I write code. For a beginner at C# you are doing a good job. No one is perfect, neither am I, we will improve with every little experience we gain :wink:

**Pull request merged**
