### PR TITLE
Fixed issue

### PR DESCRIPTION
**Pull request by mLoDar**
Created a new class for regex patterns which can be used across the project. This makes it easier to access them and not have them hard coded. This commit solved issue #18 and #21 .

### CODE REVIEW

**Comment by Lashaka** [comment]
@mLoDar  looks good,  thank you for the contribution
@Guy-S-glitch make sure to move this helper class into the Common project later on when you redesign the heirarchy

**Comment by mLoDar** [comment]
@Lashaka 
I am planing on fixing issues from time to time. Are there special naming conventions or something I should pay attention to?

**Comment by mLoDar** [comment]
Okay thanks, I will read into it and try my best to put it into practice. I am looking forward to contribute to this project! : )

**Comment by Guy-S-glitch** [comment]
hi @mLoDar.
i saw your pr and i wanted to say as a starter c# developer that your pr is helping me improve and i'm very thankful.

**Pull request merged**
